=== cltl/MFS_classifier/resources/repositories/jex_it/en-eurovoc-1.0/resources/ThesaurusStructure/langue.dtd
<!-- DTD pour le fichier des langues  -->

<!ELEMENT LANGUES (RECORD+)>

<!ELEMENT RECORD (THESAURUS_ID, DESCRIPTEUR_ID, TOPTERM)>

<!ELEMENT LIBELLE	(#PCDATA)>

<!ELEMENT COURTE	(#PCDATA)>

<!ELEMENT TRI		(#PCDATA)>

<!ATTLIST LANGUES

			VERSION	CDATA		#REQUIRED >

=== cltl/MFS_classifier/resources/repositories/jex_it/en-eurovoc-1.0/resources/ThesaurusStructure/langue.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE LANGUES SYSTEM "langue.dtd">
<LANGUES VERSION="4_3">
<RECORD>
<LIBELLE>Espagnol</LIBELLE>
<COURTE>ES</COURTE>
<TRI>spanish</TRI>
</RECORD>
<RECORD>
<LIBELLE>Danois</LIBELLE>
<COURTE>DA</COURTE>
<TRI>danish</TRI>
</RECORD>
<RECORD>
<LIBELLE>Allemand</LIBELLE>
<COURTE>DE</COURTE>
<TRI>german</TRI>
</RECORD>
<RECORD>
<LIBELLE>Grec</LIBELLE>
<COURTE>EL</COURTE>
<TRI>greek</TRI>
</RECORD>
<RECORD>
<LIBELLE>Anglais</LIBELLE>
<COURTE>EN</COURTE>
<TRI>binary</TRI>
</RECORD>
<RECORD>
<LIBELLE>Français</LIBELLE>
<COURTE>FR</COURTE>
<TRI>french</TRI>
</RECORD>
<RECORD>
<LIBELLE>Italien</LIBELLE>
<COURTE>IT</COURTE>
<TRI>italian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Néerlandais</LIBELLE>
<COURTE>NL</COURTE>
<TRI>dutch</TRI>
</RECORD>
<RECORD>
<LIBELLE>Portugais</LIBELLE>
<COURTE>PT</COURTE>
<TRI>spanish</TRI>
</RECORD>
<RECORD>
<LIBELLE>Finois</LIBELLE>
<COURTE>FI</COURTE>
<TRI>finnish</TRI>
</RECORD>
<RECORD>
<LIBELLE>Suédois</LIBELLE>
<COURTE>SV</COURTE>
<TRI>swedish</TRI>
</RECORD>
<RECORD>
<LIBELLE>Tchèque</LIBELLE>
<COURTE>CS</COURTE>
<TRI>czech</TRI>
</RECORD>
<RECORD>
<LIBELLE>Hongrois</LIBELLE>
<COURTE>HU</COURTE>
<TRI>hungarian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Polonais</LIBELLE>
<COURTE>PL</COURTE>
<TRI>polish</TRI>
</RECORD>
<RECORD>
<LIBELLE>Estonien</LIBELLE>
<COURTE>ET</COURTE>
<TRI>estonian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Letton</LIBELLE>
<COURTE>LV</COURTE>
<TRI>latvian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Lituanien</LIBELLE>
<COURTE>LT</COURTE>
<TRI>lithuanian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Maltais</LIBELLE>
<COURTE>MT</COURTE>
<TRI>binary</TRI>
</RECORD>
<RECORD>
<LIBELLE>Slovaque</LIBELLE>
<COURTE>SK</COURTE>
<TRI>slovak</TRI>
</RECORD>
<RECORD>
<LIBELLE>Slovène</LIBELLE>
<COURTE>SL</COURTE>
<TRI>slovenian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Croate</LIBELLE>
<COURTE>HR</COURTE>
<TRI>Croatian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Bulgare</LIBELLE>
<COURTE>BG</COURTE>
<TRI>Bulgarian</TRI>
</RECORD>
<RECORD>
<LIBELLE>Roumain</LIBELLE>
<COURTE>RO</COURTE>
<TRI>romanian</TRI>
</RECORD>
</LANGUES>
