=== cltl/MFS_classifier/resources/repositories/jex_it/en-eurovoc-1.0/resources/ThesaurusStructure/scope_note.dtd
<!-- DTD pour le fichier des scope-note  -->

<!ELEMENT SCOPE_NOTE (RECORD+)>

<!ELEMENT RECORD (DESCRIPTEUR_ID, SN)>

<!ELEMENT DESCRIPTEUR_ID	(#PCDATA)>

<!ELEMENT SN					(#PCDATA)>

<!ATTLIST SCOPE_NOTE

			LNG					CDATA		#REQUIRED
			VERSION				CDATA		#REQUIRED >

=== cltl/MFS_classifier/resources/repositories/jex_it/en-eurovoc-1.0/resources/ThesaurusStructure/sn_bg.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE SCOPE_NOTE SYSTEM "scope_note.dtd">
<SCOPE_NOTE LNG="BG" VERSION="4_3">
<RECORD>
<DESCRIPTEUR_ID>428</DESCRIPTEUR_ID>
<SN>Създадена през 1958 г. под името Европейска агенция за атомна енергия, организацията приема своето официално наименование през 1972 г., за да отбележи международния си обхват.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8542</DESCRIPTEUR_ID>
<SN>След реформата на Правилника за персонала на Европейските общности, влязла в сила през месец май 2004 г., функционалната група на администраторите (AD) заменя предишните категории A и LA.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>120</DESCRIPTEUR_ID>
<SN>Неактивна организация, създадена на 14 юни 1966 г. от правителствата на Австралия, Япония, Южна Корея, Южен Виетнам, Република Корея, Малайзия, Нова Зеландия и Филипините. Разпусната е през 1975 г. вследствие на липсата на съгласие на нейните членове по въпроса за признаването на Китайската народна република.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5258</DESCRIPTEUR_ID>
<SN>Институционална процедура, при която се използват механизмите от първия стълб на ЕС, за разлика от междуправителствения метод, използван при останалите стълбове.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1094</DESCRIPTEUR_ID>
<SN>Заменя Латиноамериканската асоциация за свободна търговия през 1981 г.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2070</DESCRIPTEUR_ID>
<SN>отбранителен пакт, който обвързва Австралия със Съединените щати и Нова Зеландия.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8407</DESCRIPTEUR_ID>
<SN>След реформата на Правилника за персонала на Европейските общности, влязла в сила през месец май 2004 г., функционалната група на асистентите (AST) заменя предишните категории B, C и D.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2202</DESCRIPTEUR_ID>
<SN>Панафриканска организация, която заменя Организацията за африканско единство (ОАЕ) на 9 юли 2002 г. Тя обхваща всички африкански страни, включително Западна Сахара, с изключение на Мароко.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6148</DESCRIPTEUR_ID>
<SN>От януари 2007 г. Конфедерацията на европейския бизнес се нарича БизнесЮръп (Businesseurope).</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8413</DESCRIPTEUR_ID>
<SN>Интернет сайт, на който интернет потребител води лична хроника или хроника, посветена на определена тема.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8411</DESCRIPTEUR_ID>
<SN>Принцип на международното право, съгласно който две или повече държави приемат да си сътрудничат в определена област.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5407</DESCRIPTEUR_ID>
<SN>Временно прилагане на споразумение на ЕО. Комбинира се със „споразумение за асоцииране“, „търговско споразумение“ или „споразумение за сътрудничество“.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4018</DESCRIPTEUR_ID>
<SN>Съвкупност от нормативните актове, приети от европейските институции в изпълнение на разпоредбите на договорите.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8438</DESCRIPTEUR_ID>
<SN>Наука, която има за предмет изучаването на формата, размерите и гравитационното поле на Земята.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8428</DESCRIPTEUR_ID>
<SN>Съвкупност от движения и сдружения с нестопанска цел, които са независими от държавата, и чиято цел е да променят чрез целенасочени усилия политиките, стандартите или социалните структури на национално или международно равнище.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1194</DESCRIPTEUR_ID>
<SN>Г-10 представлява министрите на финансите и управителите на централните банки на най-развитите индустриални страни към Международния валутен фонд (МВФ). Тя се състои от страните от Г-7, Белгия, Нидерландия и Швеция.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6114</DESCRIPTEUR_ID>
<SN>Група на седемте най-развити индустриални държави (Съединените щати, Япония, Германия, Франция, Италия, Обединеното кралство и Канада). През 1998 г. към нея се присъединява Русия и тя се превръща в Г-8.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3676</DESCRIPTEUR_ID>
<SN>Създадена през 1983 г. от министрите на външните работи на Мексико, Венецуела, Колумбия и Панама, групата „Контадора“ става част от Групата от Рио през 1987 г. Да се използва изразът Групата от Рио.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6116</DESCRIPTEUR_ID>
<SN>Постоянно действаща организация за политически консултации и съгласуване на становища на страните от Латинска Америка и Карибския басейн, която е резултат от сливането на групата „Контадора“ и на Групата от Лима през 1986 г.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3196</DESCRIPTEUR_ID>
<SN>Организиране на международния търговски обмен, основано на преки споразумения, сключени между отделни двойки държави.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3462</DESCRIPTEUR_ID>
<SN>Използва се за споразумение между две държави, които единствени са обвързани да спазват неговите клаузи, и от чийто изгоди обикновено не се ползват трети страни.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4480</DESCRIPTEUR_ID>
<SN>Договорът за ЕОВС е изтекъл през месец юли 2002 г.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8553</DESCRIPTEUR_ID>
<SN>В процес на ратификация.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5411</DESCRIPTEUR_ID>
<SN>Обща основа от права и задължения, която обвързва всички държави-членки в рамките на Европейския съюз.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4201</DESCRIPTEUR_ID>
<SN>Нерегистрирано дружество, което не е юридическо лице и няма правосубектност, не е задължено да обяви публично своето съществуване и може да остане незаявено.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5805</DESCRIPTEUR_ID>
<SN>Да не се бърка с „председател на институция“.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4483</DESCRIPTEUR_ID>
<SN>Военен съюз (1955—1991 г.), обвързвал Албания (до 1968 г.), ГДР, България, Унгария, Полша, Румъния и Чехословакия със Съветския съюз.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5655</DESCRIPTEUR_ID>
<SN>Политическо и регионално сътрудничество, основано през 1991 г. от Чехословашката република, Република Полша и Република Унгария. След разпадането на Чехословакия през 1993 г., в него участват четири страни, тъй като и Чешката и Словашката република продължават да членуват.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2291</DESCRIPTEUR_ID>
<SN>Политическо представителство, обхващащо държавите от Централна и Източна Европа под съветско влияние от края на Втората световна война до разпада на съветската комунистическа система през 1989—1991 г.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5087</DESCRIPTEUR_ID>
<SN>Междуправителствена икономическа организация (1949-1991 г.), основана от СССР, България, Чехословакия, Унгария, Полша и Румъния. С течение на времето към нея се присъединяват Албания (1949-1987 г.), ГДР (1950-1990 г.), Монголия (1962 г.), Куба (1972 г.) и Виетнам (1978 г.), както и Югославия (1964 г.) като асоцииран член.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5177</DESCRIPTEUR_ID>
<SN>Европейска информационна мрежа в областта на образованието.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>908</DESCRIPTEUR_ID>
<SN>Неформална асоциация на министрите на отбраната на европейските страни в рамките на НАТО, разпусната през 1994 г.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8430</DESCRIPTEUR_ID>
<SN>Процес на интегриране на политическата и икономическата динамика на ЕС при изготвянето на националните политики.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2829</DESCRIPTEUR_ID>
<SN>Основана през 1975 г. след сливането на Европейската организация за космически изследвания (ESRO/OERS) и на Европейската организация за създаване и изграждане на носители за космически апарати (ELDO/CECLES).</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6091</DESCRIPTEUR_ID>
<SN>Общ термин, обхващащ трите европейски организации по стандартизация (CEN, Cenelec и ETSI). Комбинира се с всеки отделен орган.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4603</DESCRIPTEUR_ID>
<SN>Създаден през 1950 г. от осемнадесет държави-членки на Европейската организация за икономическо сътрудничество (ЕОИС), Европейският платежен съюз е разпуснат през месец декември 1958 г. и заменен от Европейското валутно споразумение.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5948</DESCRIPTEUR_ID>
<SN>Първоначално това е била неформална консултация между държавите-членки с цел изготвяне на съгласувани позиции и съвместното прилагане на европейска външна политика. След като е придобила официална форма чрез договора за Европейския съюз, тя е заменена от Общата външна политика и политиката на сигурност. Да се използва съкращението „ОВППС“.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8488</DESCRIPTEUR_ID>
<SN>Организация, създадена през 2001 г. от сливането на Международния съюз за речно корабоплаване (UINF) и на Международния консорциум за корабоплаване по река Рейн (CINR).</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8549</DESCRIPTEUR_ID>
<SN>Целта на ЕФПГ е да помогне на работници, загубили работата си в резултат на промените в модела на международна търговия, да си намерят друга работа възможно най-бързо.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4437</DESCRIPTEUR_ID>
<SN>Наследник на Европейския платежен съюз, то представлява институционалната рамка на сътрудничеството в паричната област на държавите от Европейската организация за икономическо сътрудничество (ЕОИС) от 1958 до 1972 г.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4070</DESCRIPTEUR_ID>
<SN>Проект за координиране на външните политики между държавите-членки, започнат от началото на 70-те години. Европейското политическо сътрудничество е интегрирано в Договора за Европейския съюз и придобива официална форма чрез „Обща външна политика и политика на сигурност“. Да се използва съкращението ОВППС.</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8427</DESCRIPTEUR_ID>
<SN>Европеизиране на гражданското право на държавите-членки на Европейския съюз</SN>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6160</DESCRIPTEUR_ID>
