=== cltl/MFS_classifier/resources/repositories/jex_it/en-eurovoc-1.0/resources/ThesaurusStructure/used_for.dtd
<!-- DTD pour le fichier des used-for  -->

<!ELEMENT USED_FOR (RECORD+)>

<!ELEMENT RECORD (DESCRIPTEUR_ID, UF)>

<!ELEMENT UF (UF_EL+)>

<!ELEMENT DESCRIPTEUR_ID	(#PCDATA)>

<!ELEMENT UF_EL				(#PCDATA)>

<!ATTLIST USED_FOR

			LNG					CDATA		#REQUIRED
			VERSION				CDATA		#REQUIRED >

=== cltl/MFS_classifier/resources/repositories/jex_it/en-eurovoc-1.0/resources/ThesaurusStructure/uf_mt.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE USED_FOR SYSTEM "used_for.dtd">
<USED_FOR LNG="MT" VERSION="4_3">
<RECORD>
<DESCRIPTEUR_ID>5453</DESCRIPTEUR_ID>
<UF><UF_EL>ajruplan tal-ġlied</UF_EL>
<UF_EL>fighter</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1094</DESCRIPTEUR_ID>
<UF><UF_EL>Assoċjazzjoni Latino-Amerikana ta' Integrazzjoni</UF_EL>
<UF_EL>Assoċjazzjoni Latino-Amerikana ta' Kummerċ Ħieles [LAFTA]</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8542</DESCRIPTEUR_ID>
<UF><UF_EL>grupp ta' funzjonijiet AD</UF_EL>
<UF_EL>grupp ta' funzjonijiet ta' amministraturi</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6269</DESCRIPTEUR_ID>
<UF><UF_EL>evalwazzjoni komparattiva</UF_EL>
<UF_EL>riċerka komparattiva</UF_EL>
<UF_EL>tqabbil</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1874</DESCRIPTEUR_ID>
<UF><UF_EL>il-Prinċipat ta’ Andorra</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8470</DESCRIPTEUR_ID>
<UF><UF_EL>konservazzjoni diġitali</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1838</DESCRIPTEUR_ID>
<UF><UF_EL>L-Assoċjazzjoni tan-Nazzjonijiet tal-Ażja tax-Xlokk</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8407</DESCRIPTEUR_ID>
<UF><UF_EL>grupp ta' funzjonijiet AST</UF_EL>
<UF_EL>grupp ta' funzjonijiet ta' assistenti</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>421</DESCRIPTEUR_ID>
<UF><UF_EL>Aġenzija Ewropea tal-Produttività</UF_EL>
<UF_EL>EANPC</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5657</DESCRIPTEUR_ID>
<UF><UF_EL>kooperazzjoni bejn awtoritajiet lokali</UF_EL>
<UF_EL>kooperazzjoni interkomunali</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5446</DESCRIPTEUR_ID>
<UF><UF_EL>SAARC</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>7415</DESCRIPTEUR_ID>
<UF><UF_EL>ACS</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3312</DESCRIPTEUR_ID>
<UF><UF_EL>rinunzja tal-awtorità tal-ġenituri</UF_EL>
<UF_EL>tneħħija tal-awtorità tal-ġenituri</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1034</DESCRIPTEUR_ID>
<UF><UF_EL>IAEA</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2829</DESCRIPTEUR_ID>
<UF><UF_EL>Organizzazzjoni Ewropea għall-bini ta' pjattaformi għat-tajran ta' inġenji spazjali.</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1455</DESCRIPTEUR_ID>
<UF><UF_EL>Aġenzija speċjalizzata tan-NU</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4744</DESCRIPTEUR_ID>
<UF><UF_EL>BIAf</UF_EL>
<UF_EL>Grupp tal-Bank Afrikan tal-Iżvilupp</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4838</DESCRIPTEUR_ID>
<UF><UF_EL>BEI</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6337</DESCRIPTEUR_ID>
<UF><UF_EL>BAĊIE</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5455</DESCRIPTEUR_ID>
<UF><UF_EL>BĊE</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5460</DESCRIPTEUR_ID>
<UF><UF_EL>Bank Ewropew għar-Rikostruzzjoni u l-Iżvilupp</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4859</DESCRIPTEUR_ID>
<UF><UF_EL>l-Organizzazzjoni tal-Konsumaturi Ewropej</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>568</DESCRIPTEUR_ID>
<UF><UF_EL>agrikoltura bijoloġika</UF_EL>
<UF_EL>agrikoltura organika</UF_EL>
<UF_EL>biedja bijoloġika</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8412</DESCRIPTEUR_ID>
<UF><UF_EL>bijodiżil</UF_EL>
<UF_EL>bijoetanol</UF_EL>
<UF_EL>bijofjuwil</UF_EL>
<UF_EL>karburant li ma jniġġisx</UF_EL>
<UF_EL>petrol li ma jniġġisx</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>7410</DESCRIPTEUR_ID>
<UF><UF_EL>bijometrija</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6148</DESCRIPTEUR_ID>
<UF><UF_EL>UNICE</UF_EL>
<UF_EL>l-Unjin tal-Industriji tal-Komunità Ewropea</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5264</DESCRIPTEUR_ID>
<UF><UF_EL>Komunità tal-Karibew</UF_EL>
<UF_EL>Żona ta' Kummerċ Ħieles tal-Karibew [Carifta]</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>7185</DESCRIPTEUR_ID>
<UF><UF_EL>il-Ftehim dwar il-Kummerċ Ħieles fl-Ewropa Ċentrali</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5248</DESCRIPTEUR_ID>
<UF><UF_EL>Konferenza Ewropea tal-Amministrazzjonijiet tal-Posta u Telekomunikazzjoni</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5365</DESCRIPTEUR_ID>
<UF><UF_EL>L-Organizzazzjoni Ewropea għar-Riċerka Nukleari</UF_EL>
<UF_EL>Laboratorju Ewropew għall-Fiżika tal-Partikoli</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>118</DESCRIPTEUR_ID>
<UF><UF_EL>CCC</UF_EL>
<UF_EL>Kumitat ta' Tmexxija għall-Kultura [CDCULT]</UF_EL>
<UF_EL>Kumitat ta' Tmexxija għall-Wirt Kulturali [CDPAT]</UF_EL>
<UF_EL>Kumitat tat-Tmexxija għall-Edukazzjoni Għolja u r-Riċerka [CDESR]</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>381</DESCRIPTEUR_ID>
<UF><UF_EL>pluraliżmu politiku</UF_EL>
<UF_EL>ugwaljanza demokratika</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8423</DESCRIPTEUR_ID>
<UF><UF_EL>parteċipazzjoni demokratika</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>8424</DESCRIPTEUR_ID>
<UF><UF_EL>demokrazija indiretta</UF_EL>
<UF_EL>demokrazija parlamentari</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>950</DESCRIPTEUR_ID>
<UF><UF_EL>tkeċċija</UF_EL>
<UF_EL>tkeċċija ammnistrattiva</UF_EL>
<UF_EL>tkeċċija mit-territorju</UF_EL>
<UF_EL>ċaħda tad-dħul</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4014</DESCRIPTEUR_ID>
<UF><UF_EL>Deċiżjoni tal-Kummissjoni</UF_EL>
<UF_EL>Deċiżjoni tal-Kunsill</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5305</DESCRIPTEUR_ID>
<UF><UF_EL>analiżi tal-laboratorju</UF_EL>
<UF_EL>ekografija</UF_EL>
<UF_EL>elettroenċefalografija</UF_EL>
<UF_EL>elettrokardjografija</UF_EL>
<UF_EL>endoskopija</UF_EL>
<UF_EL>radjodijanjożi</UF_EL>
<UF_EL>radjografija</UF_EL>
<UF_EL>radjoloġija</UF_EL>
<UF_EL>riżonanza manjetika nukleari</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>459</DESCRIPTEUR_ID>
<UF><UF_EL>intollerenza reliġjuża</UF_EL>
<UF_EL>iżlamofobija</UF_EL>
<UF_EL>kristjanofobija</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3180</DESCRIPTEUR_ID>
<UF><UF_EL>DAU</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>496</DESCRIPTEUR_ID>
<UF><UF_EL>il-Commonwealth ta' Dominika</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>566</DESCRIPTEUR_ID>
<UF><UF_EL>konflitt tal-liġijiet</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3899</DESCRIPTEUR_ID>
<UF><UF_EL>libertà soċjali</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>3404</DESCRIPTEUR_ID>
<UF><UF_EL>duplikazzjoni</UF_EL>
<UF_EL>fotokopjar</UF_EL>
<UF_EL>reprografija</UF_EL>
<UF_EL>riproduzzjoni ta' dokumenti</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6358</DESCRIPTEUR_ID>
<UF><UF_EL>Kunsill Affarijiet Ekonomiċi u Finanzjarji</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>176</DESCRIPTEUR_ID>
<UF><UF_EL>Assoċjazzjoni Ewropea tal-Kummerċ Ħieles</UF_EL>
<UF_EL>Awtorità ta' Sorveljanza tal-EFTA</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>7951</DESCRIPTEUR_ID>
<UF><UF_EL>ekonomija żviluppata</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>691</DESCRIPTEUR_ID>
<UF><UF_EL>ir-Repubblika ta' El Salvador</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>7947</DESCRIPTEUR_ID>
<UF><UF_EL>emails foloz</UF_EL>
<UF_EL>spemm</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>594</DESCRIPTEUR_ID>
<UF><UF_EL>L-Istati Afrikani Assoċjati u l-Madagaskar</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5930</DESCRIPTEUR_ID>
<UF><UF_EL>ix-Xatt tal-Punent</UF_EL>
<UF_EL>l-Istrixxa ta' Gaża</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>535</DESCRIPTEUR_ID>
<UF><UF_EL>IMPEL</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5769</DESCRIPTEUR_ID>
<UF><UF_EL>aġenzija eżekuttiva</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>1087</DESCRIPTEUR_ID>
<UF><UF_EL>Kollettivitajiet territorjali tar-Repubblika Franċiża</UF_EL>
<UF_EL>Territorji barranin tar-Repubblika Franċiża</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>5278</DESCRIPTEUR_ID>
<UF><UF_EL>ITC (UNCTAD/WTO)</UF_EL>
<UF_EL>Ċentru tal-Kummerċ Internazzjonali Konġunt UNCTAD/WTO</UF_EL>
<UF_EL>Ċentru tal-Kummerċ Internazzjonali UNCTAD/WTO</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>312</DESCRIPTEUR_ID>
<UF><UF_EL>Federazzjoni Internazzjonali tas-Soċjetajiet tas-Salib l-Aħmar u tan-Nofs Qamar l-Aħmar [IFRC]</UF_EL>
<UF_EL>Is-Salib l-Aħmar</UF_EL>
<UF_EL>Kumitat Internazzjonali tas-Salib l-Aħmar [ICRC]</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6852</DESCRIPTEUR_ID>
<UF><UF_EL>Sistema Ewropea ta' Navigazzjoni bis-Satellita [Galileo]</UF_EL>
<UF_EL>Sistema Globali ta' Navigazzjoni bis-Satellita [GNSS]</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2145</DESCRIPTEUR_ID>
<UF><UF_EL>UNIDO</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4597</DESCRIPTEUR_ID>
<UF><UF_EL>UEP</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6112</DESCRIPTEUR_ID>
<UF><UF_EL>BSE</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>7928</DESCRIPTEUR_ID>
<UF><UF_EL>L-Uffiċċju Ewropew Responsabbli mir-Reklutaġġ</UF_EL>
<UF_EL>L-Uffiċċju tal-Komunitajiet Ewropej Responsabbli mir-Reklutaġġ</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6095</DESCRIPTEUR_ID>
<UF><UF_EL>Istitut Ewropew għall-Istandards fit-Telekomunikazzjoni</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>4054</DESCRIPTEUR_ID>
<UF><UF_EL>Is-Servizzi Ewropej tax-Xogħol</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>906</DESCRIPTEUR_ID>
<UF><UF_EL>Organizzazzjoni Ewropea għas-Sigurtà tan-Navigazzjoni bl-Ajru</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6723</DESCRIPTEUR_ID>
<UF><UF_EL>Aġenzija ewropea għat-tisħiħ tal-kooperazzjoni ġudizzjarja</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>2198</DESCRIPTEUR_ID>
<UF><UF_EL>L-Uffiċju tal-Istatistika tal-Komunitajiet Ewropej</UF_EL>
</UF>
</RECORD>
<RECORD>
<DESCRIPTEUR_ID>6160</DESCRIPTEUR_ID>
<UF><UF_EL>Organizzazzjoni Ewropea tat-Telekomunikazzjonijiet bis-Satellita</UF_EL>
</UF>
